/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddIcon: typeof import('./../components/timeline/icons/AddIcon.vue')['default']
    AttrEmptyIcon: typeof import('./../components/timeline/icons/AttrEmptyIcon.vue')['default']
    AudioIcon: typeof import('./../components/timeline/icons/AudioIcon.vue')['default']
    DeleteIcon: typeof import('./../components/timeline/icons/DeleteIcon.vue')['default']
    EffectsIcon: typeof import('./../components/timeline/icons/EffectsIcon.vue')['default']
    FilterIcon: typeof import('./../components/timeline/icons/FilterIcon.vue')['default']
    ImageIcon: typeof import('./../components/timeline/icons/ImageIcon.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NSlider: typeof import('naive-ui')['NSlider']
    NTooltip: typeof import('naive-ui')['NTooltip']
    RedoIcon: typeof import('./../components/timeline/icons/RedoIcon.vue')['default']
    SplitIcon: typeof import('./../components/timeline/icons/SplitIcon.vue')['default']
    SubIcon: typeof import('./../components/timeline/icons/SubIcon.vue')['default']
    SvgIcon: typeof import('./../components/svg-icon.vue')['default']
    TextIcon: typeof import('./../components/timeline/icons/TextIcon.vue')['default']
    Timeline: typeof import('./../components/timeline/index.vue')['default']
    TransitionIcon: typeof import('./../components/timeline/icons/TransitionIcon.vue')['default']
    UndoIcon: typeof import('./../components/timeline/icons/UndoIcon.vue')['default']
    VideoIcon: typeof import('./../components/timeline/icons/VideoIcon.vue')['default']
  }
}
